# Generated by Django 5.0 on 2024-01-16 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_master', '0002_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=255)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Non-binary'), (4, 'Other')])),
                ('dob', models.DateField()),
                ('mob', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('jdate', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='barcode/')),
                ('status', models.IntegerField(default=1)),
                ('deptid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.masterdpt')),
                ('desid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.masterdesig')),
                ('empcatid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.masterempcat')),
                ('qualid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.masterqualif')),
            ],
        ),
    ]
