# Generated by Django 5.0 on 2024-01-16 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_employee', '0001_initial'),
        ('admin_master', '0002_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromdate', models.DateField()),
                ('todate', models.DateField(blank=True, null=True)),
                ('deptid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.masterdpt')),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_employee.employeeregistration')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromdate', models.DateField()),
                ('todate', models.DateField(blank=True, null=True)),
                ('designationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.masterdesig')),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_employee.employeeregistration')),
            ],
        ),
        migrations.CreateModel(
            name='EmpSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fromdate', models.DateField()),
                ('todate', models.DateField(blank=True, null=True)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_employee.employeeregistration')),
            ],
        ),
    ]
